version: "2.2"

services:
  jenkins:
    image: jenkins
    mem_limit: '500M'
    cpus: '0.35' 
    container_name: jenkins
    networks: 
      - my_net
    restart: unless-stopped
    environment:
      - HOME=/var/jenkins_home
      - JENKINS_HOME=/var/jenkins_home
      - JAVA_OPTS=
          -Djenkins.install.runSetupWizard=false
          -Djava.awt.headless=true
    volumes:
      - ./jenkins_data:/var/jenkins_home/
    logging:
      options:
        tag: jenkins

  nginx:
    image: nginx
    container_name: nginx
    networks: 
      - my_net
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    logging:
      options:
        tag: nginx

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    networks: 
      - my_net
    restart: unless-stopped
    mem_limit: '1024M'
    cpus: '0.60'
    ports:
      - 8081:8081
    volumes:
      - ./nexus_data:/nexus-data/
    logging:
      options:
        tag: nexus

networks:
  my_net:
    driver: bridge
    ipam:
      config:
        - subnet: 123.45.0.0/24
  


