version: "3.6"

services:
  jenkins:
    image: jenkins
    networks: 
      - my_net
    environment:
      - HOME=/var/jenkins_home
      - JENKINS_HOME=/var/jenkins_home
      - JAVA_OPTS=
          -Djenkins.install.runSetupWizard=false
          -Djava.awt.headless=true
    volumes:
      - ./jenkins_data:/var/jenkins_home/
    logging:
      options:
        tag: jenkins
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.35'
          memory: '500M'
        reservations:
          cpus: '0.25'
          memory: '250M'  

  nginx:
    image: nginx
    networks: 
      - my_net
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    logging:
      options:
        tag: nginx
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: '300M'
        reservations:
          cpus: '0.15'
          memory: '150M'

networks:
  my_net:
    driver: overlay
    ipam:
      config:
        - subnet: 123.45.0.0/24
  


